[[constraint]]
  name = "github.com/Azure/azure-amqp-common-go"
  version = "~0.6.0"

[[constraint]]
  name = "github.com/Azure/azure-event-hubs-go"
  version = "~0.4.0"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = ">19.0.0"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = ">10.0.0"
